/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectType = IDL.Variant({
  'commercial' : IDL.Null,
  'other' : IDL.Null,
  'residential' : IDL.Null,
  'industrial' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'projectType' : ProjectType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ProjectType, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectType = IDL.Variant({
    'commercial' : IDL.Null,
    'other' : IDL.Null,
    'residential' : IDL.Null,
    'industrial' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'projectType' : ProjectType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ProjectType, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };